import { useState } from "react";
import { ArrowRight, Building2, CalendarCheck, Check, CheckCircle2, ChevronLeft, Clock3, CreditCard, HeartPulse, KeyRound, Save, ShieldCheck, Stethoscope, UserRound, Users } from "lucide-react";
import MedAlignBrand from "../components/MedAlignBrand";

const doctors = [
  { name: "Dr. Amelia Stone", specialty: "Cardiology", clinic: "Health Hub", availability: "Available today", slots: ["09:30 AM", "11:00 AM", "02:30 PM"] },
  { name: "Dr. Rahim Khan", specialty: "Neurology", clinic: "MedAlign Central", availability: "Tomorrow", slots: ["10:00 AM", "01:00 PM", "04:00 PM"] },
  { name: "Dr. Emily Wilson", specialty: "Pediatrics", clinic: "Family Care", availability: "Available today", slots: ["09:00 AM", "12:30 PM", "03:00 PM"] },
];
const clinicSteps = ["Clinic info", "Doctors", "Plan", "Payment"];
const patientSteps = ["Doctor", "Slot", "Payment", "OTP verification"];

function GetStartedPage({ onBack, onDoctorClick }) {
  const [path, setPath] = useState(null);
  const [step, setStep] = useState(1);
  const [saved, setSaved] = useState(false);
  const [completed, setCompleted] = useState(false);
  const [selectedDoctor, setSelectedDoctor] = useState(null);
  const [selectedSlot, setSelectedSlot] = useState("");
  const [plan, setPlan] = useState("Professional");
  const steps = path === "clinic" ? clinicSteps : patientSteps;
  const choosePath = (nextPath) => { setPath(nextPath); setStep(1); setCompleted(false); setSaved(false); };
  const continueFlow = () => setStep((current) => current === 4 ? current : current + 1);
  const finishFlow = () => setCompleted(true);
  const resetFlow = () => { setPath(null); setStep(1); setCompleted(false); setSaved(false); setSelectedDoctor(null); setSelectedSlot(""); };

  return <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/40 to-white text-slate-900">
    <header className="border-b border-slate-200 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5 lg:px-10"><MedAlignBrand onClick={onBack} /><div className="flex items-center gap-2 text-sm font-semibold text-blue-700"><HeartPulse className="h-5 w-5" /> Get started</div></div></header>
    <main className="mx-auto max-w-6xl px-6 py-10 lg:px-10 lg:py-14">
      {!path && <ChoiceScreen onChoose={choosePath} />}
      {path && !completed && <div className="mx-auto max-w-4xl"><div className="mb-8"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-600">{path === "clinic" ? "Clinic onboarding" : "Patient booking"}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-slate-950">{path === "clinic" ? "Set up your clinic" : "Book your consultation"}</h1><p className="mt-3 text-slate-500">Step {step} of 4 · Save your progress at any time.</p></div><Progress steps={steps} current={step} /><FlowPanel path={path} step={step} selectedDoctor={selectedDoctor} setSelectedDoctor={setSelectedDoctor} selectedSlot={selectedSlot} setSelectedSlot={setSelectedSlot} plan={plan} setPlan={setPlan} /><div className="mt-7 flex flex-wrap items-center justify-between gap-4"><button disabled={step === 1} onClick={() => setStep((current) => current - 1)} className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-600 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /> Previous</button><div className="flex flex-wrap gap-3"><button onClick={() => setSaved(true)} className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-600 hover:text-blue-700"><Save className="h-4 w-4" /> Save & continue later</button><button onClick={step === 4 ? finishFlow : continueFlow} className="inline-flex items-center gap-2 rounded-full bg-blue-700 px-6 py-3 text-sm font-semibold text-white hover:bg-blue-600">{step === 4 ? "Finish" : "Save & continue"}<ArrowRight className="h-4 w-4" /></button></div></div>{saved && <p className="mt-4 text-right text-sm font-medium text-emerald-700"><CheckCircle2 className="mr-1 inline h-4 w-4" /> Progress saved. You can resume later.</p>}</div>}
      {path && completed && <CompleteScreen path={path} onReset={resetFlow} onDoctorClick={onDoctorClick} />}
    </main>
  </div>;
}

function ChoiceScreen({ onChoose }) { return <div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.28em] text-blue-600">Get started with MedAlign</p><h1 className="mt-4 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">What brings you here?</h1><p className="mx-auto mt-4 max-w-xl text-lg leading-8 text-slate-600">Choose a path and we will guide you through the next steps.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2"><ChoiceCard icon={<Building2 />} title="I'm a Clinic" text="Set up your clinic, invite doctors, choose a plan, and start managing care." tone="blue" onClick={() => onChoose("clinic")} /><ChoiceCard icon={<UserRound />} title="I'm a Patient" text="Find a doctor, choose a time, confirm your visit, and get your queue token." tone="emerald" onClick={() => onChoose("patient")} /></div><div className="mt-8 flex items-center justify-center gap-2 text-sm text-slate-500"><ShieldCheck className="h-4 w-4 text-emerald-600" /> No password required. We use OTP verification.</div></div>; }
function ChoiceCard({ icon, title, text, tone, onClick }) { const styles = tone === "blue" ? "border-blue-200 hover:border-blue-500 hover:bg-blue-50/60 text-blue-700" : "border-emerald-200 hover:border-emerald-500 hover:bg-emerald-50/60 text-emerald-700"; return <button onClick={onClick} className={`group rounded-3xl border bg-white p-7 text-left shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${styles}`}><div className="flex items-center justify-between"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-50">{icon}</div><ArrowRight className="h-5 w-5" /></div><h2 className="mt-8 text-2xl font-semibold text-slate-950">{title}</h2><p className="mt-3 max-w-sm text-sm leading-6 text-slate-500">{text}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-semibold">Start this path <ArrowRight className="h-4 w-4" /></span></button>; }
function Progress({ steps, current }) { return <div className="mb-8"><div className="flex items-center justify-between gap-2">{steps.map((label, index) => <div key={label} className="flex min-w-0 items-center gap-2"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold ${index + 1 <= current ? "bg-blue-700 text-white" : "bg-slate-200 text-slate-500"}`}>{index + 1 < current ? <Check className="h-4 w-4" /> : index + 1}</div><span className={`hidden text-xs font-semibold sm:block ${index + 1 === current ? "text-blue-700" : "text-slate-400"}`}>{label}</span>{index < steps.length - 1 && <div className={`hidden h-px w-8 sm:block md:w-16 ${index + 1 < current ? "bg-blue-600" : "bg-slate-200"}`} />}</div>)}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-700 transition-all" style={{ width: `${(current / steps.length) * 100}%` }} /></div></div>; }
function FlowPanel({ path, step, ...props }) { return path === "clinic" ? <ClinicStep step={step} {...props} /> : <PatientStep step={step} {...props} />; }
function ClinicStep({ step, plan, setPlan }) { if (step === 1) return <Panel icon={<Building2 />} eyebrow="Step 1 · Clinic info" title="Tell us about your clinic"><div className="grid gap-4 sm:grid-cols-2"><Field label="Clinic name" placeholder="Riverside Medical Centre" /><Field label="Address" placeholder="Street, city, country" /><Field label="Primary specialty" placeholder="General medicine" /><Field label="Clinic phone" placeholder="+1 555 0100" /></div></Panel>; if (step === 2) return <Panel icon={<Users />} eyebrow="Step 2 · Add doctors" title="Build your care team"><div className="grid gap-4 sm:grid-cols-2"><Field label="Doctor name" placeholder="Dr. Full Name" /><Field label="Specialty" placeholder="Cardiology" /><Field label="Working days" placeholder="Mon - Fri" /><Field label="Hours" placeholder="09:00 AM - 05:00 PM" /></div><button className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-700"><Users className="h-4 w-4" /> Add another doctor</button></Panel>; if (step === 3) return <Panel icon={<ShieldCheck />} eyebrow="Step 3 · Choose a plan" title="Pick the plan that fits your clinic"><div className="grid gap-4 md:grid-cols-3">{[["Starter", "$49", "For small practices"], ["Professional", "$149", "For growing clinics"], ["Enterprise", "Custom", "For multi-site care"]].map(([name, price, text]) => <button key={name} onClick={() => setPlan(name)} className={`rounded-2xl border p-5 text-left ${plan === name ? "border-blue-600 bg-blue-50 ring-2 ring-blue-100" : "border-slate-200"}`}><div className="flex justify-between gap-2"><span className="font-semibold">{name}</span>{name === "Professional" && <span className="rounded-full bg-blue-700 px-2 py-1 text-[10px] font-bold uppercase text-white">Most popular</span>}</div><p className="mt-5 text-2xl font-semibold">{price}<span className="text-xs font-normal text-slate-500"> / month</span></p><p className="mt-2 text-sm text-slate-500">{text}</p></button>)}</div></Panel>; return <Panel icon={<CreditCard />} eyebrow="Step 4 · Payment" title="Secure your clinic plan"><div className="rounded-2xl bg-slate-50 p-5"><div className="flex justify-between text-sm"><span className="text-slate-500">{plan} plan</span><span className="font-semibold">{plan === "Starter" ? "$49" : plan === "Professional" ? "$149" : "Custom"}</span></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Cardholder name" placeholder="Full name" /><Field label="Card number" placeholder="0000 0000 0000 0000" /><Field label="Expiry" placeholder="MM / YY" /><Field label="CVC" placeholder="123" /></div></Panel>; }
function PatientStep({ step, selectedDoctor, setSelectedDoctor, selectedSlot, setSelectedSlot }) { if (step === 1) return <Panel icon={<Stethoscope />} eyebrow="Step 1 · Search doctor" title="Choose a specialist"><div className="grid gap-3">{doctors.map((doctor) => <button key={doctor.name} onClick={() => { setSelectedDoctor(doctor); setSelectedSlot(""); }} className={`flex items-center gap-4 rounded-2xl border p-4 text-left ${selectedDoctor?.name === doctor.name ? "border-blue-600 bg-blue-50" : "border-slate-200"}`}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-100 text-blue-700"><UserRound className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="font-semibold">{doctor.name}</p><p className="mt-1 text-sm text-blue-700">{doctor.specialty} · {doctor.clinic}</p></div><span className="text-xs font-semibold text-emerald-700">{doctor.availability}</span><CheckCircle2 className="h-5 w-5 text-slate-200" /></button>)}</div></Panel>; if (step === 2) return <Panel icon={<CalendarCheck />} eyebrow="Step 2 · Pick a slot" title="When would you like to visit?"><div className="rounded-2xl bg-slate-50 p-5"><p className="font-semibold">{selectedDoctor?.name || "Select a doctor first"}</p><p className="mt-1 text-sm text-slate-500">{selectedDoctor?.specialty || "Your selected specialist"}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{(selectedDoctor?.slots || ["09:00 AM", "11:30 AM", "03:00 PM"]).map((slot) => <button key={slot} onClick={() => setSelectedSlot(slot)} className={`rounded-2xl border p-4 text-sm font-semibold ${selectedSlot === slot ? "border-blue-600 bg-blue-700 text-white" : "border-slate-200"}`}><Clock3 className="mx-auto mb-2 h-5 w-5" />{slot}</button>)}</div></Panel>; if (step === 3) return <Panel icon={<CreditCard />} eyebrow="Step 3 · Consultation fee" title="Confirm your visit"><div className="rounded-2xl bg-slate-50 p-5"><div className="flex justify-between"><span className="text-slate-500">Consultation fee</span><span className="font-semibold">$35.00</span></div><p className="mt-2 text-sm text-slate-500">{selectedSlot || "Selected appointment slot"}</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Cardholder name" placeholder="Full name" /><Field label="Card number" placeholder="0000 0000 0000 0000" /></div></Panel>; return <Panel icon={<KeyRound />} eyebrow="Step 4 · OTP verification" title="Verify your phone"><p className="text-sm leading-6 text-slate-500">We sent a six-digit code to your phone. No password needed.</p><div className="mt-6 flex gap-2">{[1, 2, 3, 4, 5, 6].map((number) => <input key={number} maxLength="1" inputMode="numeric" aria-label={`OTP digit ${number}`} className="h-12 w-10 rounded-xl border border-slate-200 bg-slate-50 text-center text-lg font-semibold outline-none focus:border-blue-500" />)}</div></Panel>; }
function Panel({ icon, eyebrow, title, children }) { return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:p-8"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-700">{icon}</div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">{eyebrow}</p><h2 className="mt-1 text-2xl font-semibold">{title}</h2></div></div><div className="mt-7">{children}</div></section>; }
function Field({ label, placeholder }) { return <label className="block"><span className="text-sm font-medium text-slate-700">{label}</span><input placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>; }
function CompleteScreen({ path, onReset, onDoctorClick }) { const clinic = path === "clinic"; return <div className="mx-auto max-w-2xl text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-100 text-emerald-700"><CheckCircle2 className="h-8 w-8" /></div><p className="mt-7 text-sm font-semibold uppercase tracking-[0.25em] text-emerald-600">{clinic ? "Clinic onboarding complete" : "Appointment confirmed"}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-slate-950">{clinic ? "You're set up!" : "Booked!"}</h1><p className="mx-auto mt-4 max-w-lg text-lg leading-8 text-slate-600">{clinic ? "Your clinic workspace is ready. Invite your team and start coordinating every patient handoff." : "Your consultation is confirmed. Keep your queue token close and we will help you stay on time."}</p><div className="mt-8 flex flex-wrap justify-center gap-3">{clinic ? <button onClick={onDoctorClick} className="inline-flex items-center gap-2 rounded-full bg-blue-700 px-6 py-3 text-sm font-semibold text-white">Go to Dashboard <ArrowRight className="h-4 w-4" /></button> : <button onClick={onReset} className="inline-flex items-center gap-2 rounded-full bg-blue-700 px-6 py-3 text-sm font-semibold text-white">Track your queue token <ArrowRight className="h-4 w-4" /></button>}<button onClick={onReset} className="rounded-full border border-slate-200 bg-white px-6 py-3 text-sm font-semibold text-slate-600">Start another flow</button></div></div>; }

export default GetStartedPage;
